name: datawiz_test_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  cloud_firestore:
  firebase_core:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  
  firebase_auth: ^3.3.12
  google_sign_in: ^5.2.4
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.2


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: PatrickHand
  #     fonts:
  #       - asset: assets\fonts\PatrickHand-Regular.ttf